# Generated by Django 5.2.3 on 2025-11-26 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0130_alter_tools_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='buyer_order_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('count', models.DecimalField(decimal_places=3, max_digits=20)),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='تأیید شده')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.raw_material', verbose_name='لیست خرید سفارش')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.create_order', verbose_name='لیست خرید سفارش')),
            ],
            options={
                'verbose_name': 'لیست خرید مواد اولیه',
                'verbose_name_plural': 'لیست خرید مواد اولیه',
                'constraints': [models.UniqueConstraint(fields=('order', 'material'), name='unique_order_material')],
            },
        ),
    ]
