# Generated by Django 5.2.7 on 2025-11-28 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0132_buyer_order_list_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='buyeractivity',
            options={'ordering': ['-created_at'], 'verbose_name': 'فعالیت خریدار', 'verbose_name_plural': 'فعالیت\u200cهای خریدار'},
        ),
        migrations.RenameField(
            model_name='buyeractivity',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='buyeractivity',
            name='doing_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انجام '),
        ),
    ]
