# Generated by Django 5.2.7 on 2025-11-28 23:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0133_alter_buyeractivity_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='buyeractivity',
            name='mentioned_users',
            field=models.ManyToManyField(blank=True, related_name='mentioned_in_activities', to=settings.AUTH_USER_MODEL, verbose_name='کاربران منشن\u200cشده'),
        ),
    ]
