# Generated by Django 5.2.3 on 2025-11-29 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeTracker', '0008_commenttask'),
        ('users', '0135_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='admin_teams',
            field=models.ManyToManyField(blank=True, related_name='admins', to='timeTracker.team'),
        ),
        migrations.AddField(
            model_name='profile',
            name='teams',
            field=models.ManyToManyField(blank=True, related_name='members', to='timeTracker.team'),
        ),
    ]
