# Generated by Django 5.2.3 on 2025-11-30 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0136_profile_admin_teams_profile_teams'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileShortcuts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.CharField(max_length=300, unique=True)),
                ('content', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('icon', models.CharField(choices=[('⚙️', '⚙️ تنظیمات'), ('📊', '📊 گزارش / داشبورد'), ('🍽️', '🍽️ غذا / منو'), ('📦', '📦 انبار / کالا'), ('💰', '💰 مالی / هزینه'), ('🧮', '🧮 محاسبات / ابزار'), ('📅', '📅 برنامه\u200cریزی / زمان\u200cبندی'), ('🔧', '🔧 ابزار / تنظیمات فنی'), ('🧾', '🧾 فاکتور / سند'), ('🧠', '🧠 هوش / AI')], default='⚙️', max_length=10, verbose_name='آیکون')),
                ('category', models.CharField(default='عمومی', max_length=100)),
                ('status', models.CharField(choices=[('ready', 'آماده'), ('dev', 'در حال توسعه')], default='ready', max_length=50)),
                ('show', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-title'],
            },
        ),
    ]
