# Generated by Django 5.2.3 on 2025-12-02 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0137_profileshortcuts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyeractivity',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ ثبت'),
        ),
    ]
