# Generated by Django 5.2.7 on 2025-12-12 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0138_alter_buyeractivity_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tools',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
