# Generated by Django 5.2.7 on 2025-12-12 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0139_tools_show'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
