# Generated by Django 5.2.7 on 2025-12-12 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0140_menuitem_show'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=500)),
                ('user', models.CharField(max_length=150)),
                ('user_agent', models.TextField()),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
