# Generated by Django 5.2.7 on 2025-12-12 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0141_servererrorlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='servererrorlog',
            name='error_type',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
    ]
