# Generated by Django 5.2.3 on 2025-12-15 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0002_city_project_persons_project_city'),
        ('users', '0142_servererrorlog_error_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='entryexitlog',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Projects.project'),
        ),
    ]
