# Generated by Django 5.2.3 on 2025-07-29 13:05

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeTracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='goal_time',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Estimated time to complete (in hours)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.25'))]),
            preserve_default=False,
        ),
    ]
