# Generated by Django 5.2.3 on 2025-08-03 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeTracker', '0002_task_goal_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
