# Generated by Django 5.2.3 on 2025-08-03 12:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeTracker', '0004_task_user_delete'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeentry',
            name='date',
        ),
        migrations.AddField(
            model_name='timeentry',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
