# Generated by Django 5.2.3 on 2025-08-03 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeTracker', '0005_remove_timeentry_date_timeentry_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='priority',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.IntegerField(default=0),
        ),
    ]
