# Generated by Django 5.2.3 on 2025-08-05 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeTracker', '0006_story_priority_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
