# Generated by Django 5.2.3 on 2025-12-09 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeTracker', '0008_commenttask'),
        ('users', '0138_alter_buyeractivity_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.projects'),
        ),
    ]
