# Generated by Django 5.2.3 on 2025-12-10 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0002_city_project_persons_project_city'),
        ('timeTracker', '0009_story_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Projects.project'),
        ),
    ]
