# Generated by Django 5.2.3 on 2025-12-29 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeTracker', '0010_alter_story_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='sprint',
            name='total_hours',
            field=models.IntegerField(default=0),
        ),
    ]
