# Generated by Django 5.2.7 on 2026-01-02 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HotelManagment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='show_in_list',
            field=models.BooleanField(default=True),
        ),
    ]
