# Generated by Django 5.1.1 on 2025-08-08 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TasksManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
