# Generated by Django 5.1.1 on 2025-08-08 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TasksManager', '0002_task_is_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commenttask',
            name='created_date',
            field=models.DateField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
    ]
