# Generated by Django 5.2.3 on 2025-08-10 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Missions', '0002_mission_end_date_mission_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mission',
            name='start_date',
            field=models.DateTimeField(),
        ),
    ]
