# Generated by Django 5.2.3 on 2025-08-10 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Missions', '0003_alter_mission_end_date_alter_mission_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mission',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
