# Generated by Django 5.2.3 on 2025-08-10 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Missions', '0005_missioncomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='goals',
            field=models.TextField(blank=True),
        ),
    ]
