# Generated by Django 5.2.3 on 2025-08-11 11:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Missions', '0006_mission_goals'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowStepTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('position', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='FlowTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Flow', max_length=120)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='MissionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='mission',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='missionflow',
            options={'ordering': ['mission', 'position']},
        ),
        migrations.AddField(
            model_name='missionflow',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='missionflow',
            name='is_current',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='missionflow',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='missionflow',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='missionflow',
            unique_together={('mission', 'position')},
        ),
        migrations.AddIndex(
            model_name='missionapproval',
            index=models.Index(fields=['flow', 'user'], name='Missions_mi_flow_id_9431f1_idx'),
        ),
        migrations.AddIndex(
            model_name='missionapproval',
            index=models.Index(fields=['flow', 'approved'], name='Missions_mi_flow_id_e913a2_idx'),
        ),
        migrations.AddIndex(
            model_name='missionflow',
            index=models.Index(fields=['mission', 'position'], name='Missions_mi_mission_57b996_idx'),
        ),
        migrations.AddIndex(
            model_name='missionflow',
            index=models.Index(fields=['mission', 'is_current'], name='Missions_mi_mission_5946af_idx'),
        ),
        migrations.AddField(
            model_name='flowsteptemplate',
            name='approver_users',
            field=models.ManyToManyField(blank=True, related_name='flow_step_templates_as_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='flowsteptemplate',
            name='flow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='Missions.flowtemplate'),
        ),
        migrations.AddField(
            model_name='flowtemplate',
            name='mission_type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='flow_template', to='Missions.missiontype'),
        ),
        migrations.AddField(
            model_name='mission',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='missions', to='Missions.missiontype'),
        ),
        migrations.AlterUniqueTogether(
            name='flowsteptemplate',
            unique_together={('flow', 'position')},
        ),
    ]
