# Generated by Django 5.2.3 on 2025-08-11 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Missions', '0007_flowsteptemplate_flowtemplate_missiontype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missionflow',
            name='position',
            field=models.PositiveIntegerField(),
        ),
    ]
