# Generated by Django 5.2.3 on 2025-12-10 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketcategory',
            name='is_project',
            field=models.BooleanField(default=True),
        ),
    ]
