# Generated by Django 5.2.3 on 2025-12-10 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0002_ticketcategory_is_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketcategory',
            name='is_project',
            field=models.BooleanField(default=False),
        ),
    ]
