# Generated by Django 5.2.3 on 2025-12-10 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0005_remove_ticketmessage_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.BigIntegerField(blank=True, null=True, verbose_name='شماره تماس')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان تیکت')),
                ('message', models.TextField(verbose_name='پیام')),
                ('status', models.CharField(choices=[('open', 'باز'), ('in_progress', 'در حال بررسی'), ('closed', 'بسته شده')], default='open', max_length=20, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='utils.ticketcategory', verbose_name='دسته\u200cبندی')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectTicketMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.BigIntegerField(blank=True, null=True, verbose_name='شماره تماس')),
                ('message', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='ticket_attachments/')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_project_ticket', to='utils.projectticket')),
            ],
        ),
    ]
