# Generated by Django 5.2.3 on 2025-12-13 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Projects', '0002_city_project_persons_project_city'),
        ('utils', '0006_projectticket_projectticketmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectticket',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='Projects.project', verbose_name='پروژه'),
        ),
    ]
