# Generated by Django 5.2.3 on 2025-12-13 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0007_projectticket_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectticket',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='project_ticket_attachments/'),
        ),
    ]
