# Generated by Django 5.2.3 on 2025-12-13 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utils', '0008_projectticket_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectticket',
            name='attachment',
        ),
        migrations.AddField(
            model_name='projectticket',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='project_tickets/images/'),
        ),
    ]
